server:
  port: 8889

spring:
  application:
    name: consumer

  cloud:
      nacos:
        discovery:
          server-addr: 172.31.40.130:8848
feign:
  hystrix:
    enabled: false
  #  client:
  #    config:
  #      default:
  #        connectTimeout: 10000
  #        readTimeout: 10000


